from enum import Enum
from cv2.cv2 import ROTATE_90_CLOCKWISE, ROTATE_90_COUNTERCLOCKWISE, ROTATE_180


class CvRotations(Enum):
    CLOCK_90 = ROTATE_90_CLOCKWISE
    COUNTER_CLOCK_90 = ROTATE_90_COUNTERCLOCKWISE
    ROTATE_180 = ROTATE_180
